python generation.py --examples "100" --model 'google/gemma-2-9b-it' --source 'Franklin/full_study.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'google/gemma-2-9b-it' --source 'GSM8k/test.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'google/gemma-2-9b-it' --source 'HotpotQA/hotpot_test_fullwiki_v1.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'google/gemma-2-9b-it' --source 'StrategyQA/dev.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'meta-llama/Meta-Llama-3.1-8B-Instruct' --source 'Franklin/full_study.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'meta-llama/Meta-Llama-3.1-8B-Instruct' --source 'GSM8k/test.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'meta-llama/Meta-Llama-3.1-8B-Instruct' --source 'HotpotQA/hotpot_test_fullwiki_v1.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'meta-llama/Meta-Llama-3.1-8B-Instruct' --source 'StrategyQA/dev.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'microsoft/Phi-3.5-mini-instruct' --source 'Franklin/full_study.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'microsoft/Phi-3.5-mini-instruct' --source 'GSM8k/test.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'microsoft/Phi-3.5-mini-instruct' --source 'HotpotQA/hotpot_test_fullwiki_v1.jsonl' --description 'Random sample of 100' --save
python generation.py --examples "100" --model 'microsoft/Phi-3.5-mini-instruct' --source 'StrategyQA/dev.jsonl' --description 'Random sample of 100' --save